

-- DROP ROLE "EDOCREGISTER";
-- 
-- CREATE ROLE "EDOCREGISTER" LOGIN
--   ENCRYPTED PASSWORD 'md5366e3db0ac199ec95c1758b91641aa96'
--   NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;



GRANT SELECT, INSERT, UPDATE, DELETE ON business_partner TO "EDOCREGISTER";
GRANT SELECT, INSERT, UPDATE, DELETE ON business_partner TO "EDOCREGISTER";
GRANT SELECT, INSERT, UPDATE, DELETE ON business_partner TO "EDOCREGISTER";
GRANT SELECT, INSERT, UPDATE, DELETE ON business_partner TO "EDOCREGISTER";

GRANT SELECT ON v_XXXX TO "EDOCREGISTER";

GRANT EXECUTE ON FUNCTION_NAME TO "EDOCREGISTER";

